version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: anonwall
    environment:
      POSTGRES_USER: root1
      POSTGRES_PASSWORD: root1
      POSTGRES_DB: db1
    ports:
      - "5431:5432"